version: 3.13.1
buildTime: 20171121-171829
SVNUserName: zhipeng
SVNPassWord: zhipeng001
MakeClass.DBSExportPath: null
MakeClass.DBSTemplatePath: null
miniPay.codeGenerate.rpcGenerate.ConfigPath: '/Users/peng.zhi/Documents/Object/minipay/minipay-code-template (trunk)/CodeTemplates/conf'
miniPay.codeGenerate.rpcGenerate.TemplatePath: '/Users/peng.zhi/Documents/Object/minipay/minipay-code-template (trunk)/CodeTemplates/Rpc'
miniPay.codeGenerate.rpcGenerate.ExportPath: '/Users/peng.zhi/Documents/Object/minipay/minipay-code-template (trunk)/Generator/Logics'
miniPay.codeGenerate.rpcGenerate.ExportTestsPath: '/Users/peng.zhi/Documents/Object/minipay/minipay-code-template (trunk)/Generator/TestUnit'
miniPay.codeGenerate.rpcGenerate.ExportBridgePath: '/Users/peng.zhi/Documents/Object/minipay/minipay-code-template (trunk)/Generator/RpcBridge'
miniPay.codeGenerate.rpcGenerate.templateJsPath: '/Users/peng.zhi/Documents/paymini/minipay-code-template (trunk)/CodeTemplates/Rpc/SDKManage'
miniPay.codeGenerate.rpcGenerate.exportJsApiUrlPath: '/Users/peng.zhi/Documents/paymini/manage-console/minipay-manage-console (trunk)/codeTemplate'
miniPay.codeGenerate.rpcGenerate.templateVueRpcPath: '/Users/peng.zhi/Documents/paymini/minipay-code-template (trunk)/CodeTemplates/Rpc/Client'
miniPay.codeGenerate.rpcGenerate.exportVueRpcPath: '/Users/peng.zhi/Documents/paymini/web-weixin-merchant (trunk)/WXMerchant/src/api/Template'
miniPay.codeGenerate.rpcGenerate2.ConfigPath: /Users/peng.zhi/Documents/Object/minipay/minipay-code-template-gitlab/CodeTemplates/conf
miniPay.codeGenerate.rpcGenerate2.TemplatePath: /Users/peng.zhi/Documents/Object/minipay/minipay-code-template-gitlab/CodeTemplates/Rpc
miniPay.codeGenerate.rpcGenerate2.ExportPath: /Users/peng.zhi/Documents/Object/minipay/minipay-code-template-gitlab/src/miniPayCenter/RpcCodeTemplates
miniPay.codeGenerate.rpcGenerate2.NameSpace: bala\codeTemplate
